// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type PriceHistory struct {
	ID          int32     `json:"id"`
	ProductID   int64     `json:"product_id"`
	PriceActual int64     `json:"price_actual"`
	Quantity    int64     `json:"quantity"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Product struct {
	ID             int32     `json:"id"`
	Marketplace    string    `json:"marketplace"`
	ProductID      string    `json:"product_id"`
	Brand          string    `json:"brand"`
	Name           string    `json:"name"`
	Supplier       string    `json:"supplier"`
	SupplierRating float64   `json:"supplier_rating"`
	ProductRating  float64   `json:"product_rating"`
	Feedbacks      int64     `json:"feedbacks"`
	PriceBasic     int64     `json:"price_basic"`
	PriceActual    int64     `json:"price_actual"`
	Quantity       int64     `json:"quantity"`
	UpdatedAt      time.Time `json:"updated_at"`
}
