// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
    marketplace,
    product_id,
    brand,
    name,
    supplier,
    supplier_rating,
    product_rating,
    feedbacks,
    price_basic,
    price_actual,
    quantity
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (marketplace, product_id) 
DO UPDATE SET 
    (brand, name, supplier, supplier_rating, product_rating, feedbacks, price_basic, price_actual, quantity, updated_at) = 
    (EXCLUDED.brand, EXCLUDED.name, EXCLUDED.supplier, EXCLUDED.supplier_rating, 
     EXCLUDED.product_rating, EXCLUDED.feedbacks, EXCLUDED.price_basic, EXCLUDED.price_actual, EXCLUDED.quantity, NOW())
`

type CreateProductParams struct {
	Marketplace    string  `json:"marketplace"`
	ProductID      string  `json:"product_id"`
	Brand          string  `json:"brand"`
	Name           string  `json:"name"`
	Supplier       string  `json:"supplier"`
	SupplierRating float64 `json:"supplier_rating"`
	ProductRating  float64 `json:"product_rating"`
	Feedbacks      int64   `json:"feedbacks"`
	PriceBasic     int64   `json:"price_basic"`
	PriceActual    int64   `json:"price_actual"`
	Quantity       int64   `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.Marketplace,
		arg.ProductID,
		arg.Brand,
		arg.Name,
		arg.Supplier,
		arg.SupplierRating,
		arg.ProductRating,
		arg.Feedbacks,
		arg.PriceBasic,
		arg.PriceActual,
		arg.Quantity,
	)
	return err
}

const selectAllProducts = `-- name: SelectAllProducts :many
SELECT id, marketplace, product_id, brand, name, supplier, supplier_rating, product_rating, feedbacks, price_basic, price_actual, quantity, updated_at FROM products
ORDER BY marketplace
`

func (q *Queries) SelectAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, selectAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Marketplace,
			&i.ProductID,
			&i.Brand,
			&i.Name,
			&i.Supplier,
			&i.SupplierRating,
			&i.ProductRating,
			&i.Feedbacks,
			&i.PriceBasic,
			&i.PriceActual,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
